# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Floral
version:      1.03
version_from: lib/Acme/Floral.pm
installdirs:  site
requires:
    B::Deobfuscate:                0.10
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
