#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Floral
license:      perl
version:      1.02
version_from: lib/Acme/Floral.pm
installdirs:  site
requires:
    B::Deobfuscate:                0.10

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
